# Site settings
title: Kouding
email: xavier.woo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Obviously, this is a private blog...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

github_username:  xavierwoo

# Build settings
markdown: kramdown

highlighter: rouge